# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 06:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pin', models.TextField()),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ARRIVED_HOLDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfilled', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 6, 53, 17, 59256, tzinfo=utc))),
                ('arrival_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DEPARTURE_HOLDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfilled', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 6, 53, 17, 58112, tzinfo=utc))),
                ('expected_date', models.TextField()),
                ('terminal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PACKAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField()),
                ('sender_phone', models.TextField()),
                ('receiver_name', models.TextField()),
                ('receiver_phone', models.TextField()),
                ('destination', models.TextField()),
                ('init_weight', models.TextField()),
                ('init_price', models.TextField()),
                ('description', models.TextField()),
                ('packagenum', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 6, 53, 17, 61403, tzinfo=utc))),
                ('arrived_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ARRIVED_HOLDER')),
                ('departure_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DEPARTURE_HOLDER')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_HOLDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfilled', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 6, 53, 17, 56813, tzinfo=utc))),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PICKUP_HOLDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfilled', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 6, 53, 17, 60318, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='SEARCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isregistered', models.BooleanField(default=False)),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('action', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pickup_holder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.STATUS'),
        ),
        migrations.AddField(
            model_name='payment_holder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.STATUS'),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PAYMENT_HOLDER'),
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PICKUP_HOLDER'),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.STATUS'),
        ),
        migrations.AddField(
            model_name='departure_holder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.STATUS'),
        ),
        migrations.AddField(
            model_name='arrived_holder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.STATUS'),
        ),
    ]
