# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 2, 50, 83609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 2, 50, 82466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrived_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ARRIVED_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 2, 50, 85774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DEPARTURE_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='init_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='init_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PAYMENT_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PICKUP_HOLDER'),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 2, 50, 81181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 2, 50, 84677, tzinfo=utc)),
        ),
    ]
