# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190715_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACKAGETEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 536504, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 532367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 531217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 534541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 530016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 13, 0, 533425, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='packagetest',
            name='payment_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PAYMENT_HOLDER'),
        ),
    ]
