# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190715_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 224611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 223505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 226749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 228933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='payment_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PAYMENT_HOLDER'),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 222297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 15, 42, 225646, tzinfo=utc)),
        ),
    ]
