# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190715_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 296619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 295480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrived_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ARRIVED_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 298787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DEPARTURE_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PAYMENT_HOLDER'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PICKUP_HOLDER'),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 300769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 294280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 8, 37, 25, 297680, tzinfo=utc)),
        ),
    ]
