# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190715_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 4, 47, 620272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 4, 47, 619122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 4, 47, 622482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 4, 47, 624435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 4, 47, 617894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 4, 47, 621322, tzinfo=utc)),
        ),
    ]
