# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190715_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 2, 551489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 2, 550370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 2, 553619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 6, 2, 555811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 2, 549130, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 2, 552542, tzinfo=utc)),
        ),
    ]
