# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190715_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 899685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 898574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 901790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 903957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 897359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 6, 18, 900722, tzinfo=utc)),
        ),
    ]
