# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190715_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 23, 16, 218384, tzinfo=utc), verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 29581, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 34934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 33530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 37092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 39297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 32199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 22, 52, 36005, tzinfo=utc)),
        ),
    ]
