# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-15 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190715_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrived_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 715442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='departure_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 713723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 717919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagetest',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 720351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 712356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pickup_holder',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 716668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 15, 19, 23, 26, 710001, tzinfo=utc)),
        ),
    ]
